# Generated by Django 6.0 on 2025-12-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('url', models.URLField()),
                ('posted_at', models.DateTimeField()),
            ],
        ),
    ]
